### Device Manager configuration file
Host: device-manager
Port: 45003

PKIRootCACertificatePath: "/etc/deviceManager/certs/rootCA.crt"
PKIPrivateKeyPath: "/etc/deviceManager/certs/odimra_server.key"
PKICertificatePath: "/etc/deviceManager/certs/odimra_server.crt"

TLSConf:
  ### Supported TLS versions:
  #	VersionTLS12 = 0x0303
  #	VersionTLS13 = 0x0304
  MinVersion: 0x0303
  MaxVersion: 0x0303

### Basic Authentication
UserName: admin
Password: #insert_your_password_here

### Redfish service root UUID for Device Manager
RootServiceUUID: 99999999-9999-9999-9999-999999999999
FirmwareVersion: v1.0.0
